version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=messenger
      - POSTGRES_PASSWORD=localdbpass
    ports:
      - '5432:5432'
  server:
    build: server/
    restart: unless-stopped
    command: npm run start:dev
    ports:
      - '3001:80'
    depends_on:
      - db


